### ISSUE TITLE
[Bug]: can't pass classes to client constructor with "type": "module"

### ISSUE THREAD

**Issue by ohmree** [oceanroleplay/discord.ts#218] opened 2021-11-08 17:49 UTC
### What happened?

I'm working on an esm-only project (one of my dependencies requires it and it's viral so I must use it too) and tried passing a glob that's used to find `@Discord()` classes.

Node complains about `require` not being supported with `"type": "module"` (I believe [this is the problematic code](https://github.com/oceanroleplay/discord.ts/blob/7043e1444e04e955e33651980a0aa67ce0f04c15/src/logic/metadatas/MetadataStorage.ts#L203)).

I also can't seem to pass a list of class objects anymore (coming from `@typeit/discord`), is that on purpose? Because that would solve this issue as well.

### Reproduction

In `package.json`:
```json
// ...
"type": "module",
// ...
```
In `src/index.ts`:
```ts
import discordx from 'discordx';
const {Client} = discordx;

const discordClient = new Client({
  botId: 'test',
  classes: [path.resolve(getDirname(), 'discords/*.{ts,js}')], // getDirname is __dirname for esm, you can assume it works the same. 
  silent: false,
  intents: [/* ... */],
});
```
Run like this:
```
$ node --loader ts-node/esm/transpile-only src/index.ts
```

Actually doing the dynamic loading of classes shouldn't be too hard (just use `import()`), but I'm not sure how I would conditionally do this or `require()` in commonjs mode.
Maybe use the newer syntax and rely on the typescript compiler to produce commonjs-compatible code?

### Version

Dev

### Relevant log output

```shell
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/ohmree/code/js/contest_buddy/packages/server/src/discords/app-discord.ts
require() of ES modules is not supported.
require() of /home/ohmree/code/js/contest_buddy/packages/server/src/discords/app-discord.ts from /home/ohmree/code/js/contest_buddy/node_modules/.pnpm/discordx@9.0.0-dev.1636374790.51b604b/node_modules/discordx/build/logic/metadatas/MetadataStorage.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from /home/ohmree/code/js/contest_buddy/packages/server/package.json.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VictoriqueMoe** [comment] 2021-11-08 18:07
In order to prepare for TypeScript 4.5, we need to remove all `require` statements unless defined in a `.cts` file and compiled with TS 4.5.

All imports should define filetype:
`import { helper } from "./foo.js";`
OR
`import foo from "./foo.cjs";` for a Common JS import.

Work is required to change this, especially globbing,

for example for glob:
`import {glob} from "glob";`

**Comment by VictoriqueMoe** [comment] 2021-11-08 18:09
to add to this:
`imports.forEach((file) => require(file));` can become:
```ts
 const pArr = imports.map(file=> import(path.resolve(file)));
return Promise.all(pArr);
```

**Comment by VictoriqueMoe** [comment] 2021-11-08 18:11
@oceanroleplay i would add this to the project for Discordx 9.0

**Comment by ohmree** [comment] 2021-11-08 18:32
What about passing the actual imported classes instead of glob strings? Is that a planned feature or was it removed for a reason?

**Comment by VictoriqueMoe** [comment] 2021-11-08 18:35
> 
> 
> What about passing the actual imported classes instead of glob strings? Is that a planned feature or was it removed for a reason?

passing the actual class? you mean hard coding them? glob isn't an issue, i should fix this tonight for you

**Comment by ohmree** [comment] 2021-11-08 18:35
> > What about passing the actual imported classes instead of glob strings? Is that a planned feature or was it removed for a reason?
> 
> passing the actual class? you mean hard coding them? glob isn't an issue, i should fix this tonight for you

Something like this:
```ts
// discords/app-discord.ts
abstrac

**Comment by VictoriqueMoe** [comment] 2021-11-08 18:37
> 
> 
> > > What about passing the actual imported classes instead of glob strings? Is that a planned feature or was it removed for a reason?
> > 
> > 
> > passing the actual class? you mean hard coding them? glob isn't an issue, i should fix this tonight for you
> 
> Something like this:
> 
> ```ts
> // discords/app-discord.ts
> @Discord()
> abstract class AppDiscord { /* ... */ }
> export default AppDiscord;
> // index.ts
> import AppDiscord from 'discords/app-discord.js';
> const client = new Client({classes: [AppDiscord]});
> ```

because hard coding a massive list of files is a pain, and importing them all at startup can cause serious circular dependency issues

**Comment by VictoriqueMoe** [comment] 2021-11-08 18:40
> 
> 
> > > > > What about passing the actual imported classes instead of glob strings? Is that a planned feature or was it removed for a reason?
> > > > 
> > > > 
> > > > passing the actual class? you mean hard coding them? glob isn't an issue, i should fix this tonight for you
> > > 
> > > 
> > > Something like this:
> > > ```ts
> > > // discords/app-discord.ts
> > > @Discord()
> > > abstract class AppDiscord { /* ... */ }
> > > export default AppDiscord;
> > > // index.ts
> > > import AppDiscord from 'discords/app-discord.js';
> > > const client = new Client({classes: [AppDiscord]});
> > > ```
> > 
> > 
> > because hard coding a massive list of files is a pain, and importing them all at startup can cause serious circular dependency issues
> 
> I see. Well, as long as there's a legitimate reason for this change it's okay.

been meaning to fix this for a while. i will raise a PR tonight and hopefully get this sorted for ES modules only people (assuming DJS or any module from any plugin we use doesn't have a `require` statement) and if it does, then we will have to wait until TS 4.5, i have this issue with NodeFetch

**Comment by oceanroleplay** [comment] 2021-11-08 19:44
@ohmree one question. you are trying to work on esm only project but you should know that, discordx and discord.js are commonjs modules.

**Comment by ohmree** [comment] 2021-11-08 19:51
> @ohmree one question. you are trying to work on esm only project but you should know that, discordx and discord.js are commonjs modules.

Idk, I just write code like I normally would and fix it whenever the compiler yells at me.
Sometimes (like with discordx and prisma iirc) I need to change this:
```ts
import {Foo} from 'bar';
```
Into something like this:
```ts
import bar_pkg from 'bar';
const {Foo} = bar_pkg;
```
And then everything just works™️

**Comment by VictoriqueMoe** [comment] 2021-11-08 20:05
given the config of:

```json
"type": "module",
```
in `package.json` then applying:
```json
"module": "ES2020",
```
in `tsconfig.json` 

It seems rather hard to get a PURE ES node working in discordx. not alone the strange errors i get like `CustomError: Cannot find module 'C:\Users\Victorique\IdeaProjects\discord.ts\src\Client' imported from C:\Users\Victorique\IdeaProjects\discord.ts\examples\slash\Main.ts` using `node --loader ts-node/esm examples/slash/Main.ts`

it would seem ES nodes are not even fully supported in TS until TS 4.5 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#ecmascript-module-support-in-nodejs

For this reason, until 4.5 is out, this task will be TODO

**Comment by ohmree** [comment] 2021-11-08 20:22
> given the config of:
> 
> ```json
> "type": "module",
> ```
> 
> in `package.json` then applying:
> 
> ```json
> "module": "ES2020",
> ```
> 
> in `tsconfig.json`
> 
> It seems rather hard to get a PURE ES node working in discordx. not alone the strange errors i get like `CustomError: Cannot find module 'C:\Users\Victorique\IdeaProjects\discord.ts\src\Client' imported from C:\Users\Victorique\IdeaProjects\discord.ts\examples\slash\Main.ts` using `node --loader ts-node/esm examples/slash/Main.ts`
> 
> it would seem ES nodes are not even fully supported in TS until TS 4.5 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#ecmascript-module-support-in-nodejs
> 
> For this reason, until 4.5 is out, this task will be TODO

I'm not quite sure I get you.
Previously (with `@typeit/discord`) I would just import the classes and do `new Client({classes: [Discord1, Discord2, ...]})` and it worked fine under a pure esm environment with this config:
```json
// package.json
...
"type": "module",
...
```
```json
// tsconfig.json
...
"target": "ESNext",
"module": "ESNext",
...
```
I'd like to look into this so if you could set up a small reproduction repo it'd be really nice.
Unless you're 100% sure typescript is the blocker here, in which case you probably know better than me (but I'd still be interested in looking into this :P).

**Comment by oceanroleplay** [comment] 2021-11-09 05:53
> > given the config of:
> > ```json
> > "type": "module",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in `package.json` then applying:
> > ```json
> > "module": "ES2020",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in `tsconfig.json`
> > It seems rather hard to get a PURE ES node working in discordx. not alone the strange errors i get like `CustomError: Cannot find module 'C:\Users\Victorique\IdeaProjects\discord.ts\src\Client' imported from C:\Users\Victorique\IdeaProjects\discord.ts\examples\slash\Main.ts` using `node --loader ts-node/esm examples/slash/Main.ts`
> > it would seem ES nodes are not even fully supported in TS until TS 4.5 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#ecmascript-module-support-in-nodejs
> > For this reason, until 4.5 is out, this task will be TODO
> 
> I'm not quite sure I get you. Previously (with `@typeit/discord`) I would just import the classes and do `new Client({classes: [Discord1, Discord2, ...]})` and it worked fine under a pure esm environment with this config:
> 
> ```json
> // package.json
> ...
> "type": "module",
> ...
> ```
> 
> ```json
> // tsconfig.json
> ...
> "target": "ESNext",
> "module": "ESNext",
> ...
> ```
> 
> I'd like to look into this so if you could set up a small reproduction repo it'd be really nice. Unless you're 100% sure typescript is the blocker here, in which case you probably know better than me (but I'd still be interested in looking into this :P).
> 
> EDIT: I could also post my code if it's of any interest. An older version is on github atm but I've hacked on it quite a lot since then and I have terrible commit etiquette so it's a bit of a mess right now.

you can just import all the files in your index and don't use classes, it will work the same.

**Comment by oceanroleplay** [comment] 2021-11-09 05:54
I am not sure, how pure esm project work with commonjs dependencies.

**Comment by oceanroleplay** [comment] 2021-11-09 05:59
@VictoriqueMoe at final thinking, we can not target the project to esm.

@ohmree I could not reproduce the error mentioned in this issue, can you provide full code to reproduce this.?

**Comment by oceanroleplay** [comment] 2021-11-09 07:05
importing files like this work for me

```ts
import "./discords/common.js";
```

**Comment by oceanroleplay** [comment] 2021-11-09 07:17
> to add to this: `imports.forEach((file) => require(file));` can become:
> 
> ```ts
> const pArr = imports.map(file=> import(path.resolve(file)));
> return Promise.all(pArr);
> ```

Mentioned improvement has been pushed to main

**Comment by oceanroleplay** [comment] 2021-11-09 08:31
> I am not sure, how pure esm project work with commonjs dependencies.

I tried, but I don't think a pure ESM package can be created with commonjs dependencies. so I am gonna close this issue for now and whenever in future it is possible to change our module to commonjs, we will do it without delay. But it's not the time.

**Comment by oceanroleplay** [comment] 2021-11-09 19:38
pardon me, this should be resolve.

**Comment by oceanroleplay** [comment] 2021-11-09 19:39
@ohmree can you join our discord server for more talk?

**Closed** 2021-11-10 12:23 UTC
Labels: enhancement, package:discordx, verified

**Comment by oceanroleplay** [comment] 2021-11-10 12:25
While testing ESM support, I discovered that discordjs voice was not yet supported by ESM, so keep an eye out for that.
